# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160909_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='glyph',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
